title: Avinash's Idea Lab
description: A journey through my random, creative pursuits.
theme: just-the-docs

url: https://avinash1419.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
